import type { NextPage } from "next";
import Head from "next/head";
import { About } from "../components/About";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <About />
      </main>
    </div>
  );
};

export default Home;
